name: helium_api_client
description: A client for the Helium API (docs.helium.com/api/)
version: 0.1.0
homepage: https://github.com/jamesdobson/dart_helium_api_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: '>=0.13.1 <0.14.0'
  json_annotation: '>=4.1.0 <5.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  json_serializable: '>=5.0.0 <6.0.0'
  build_runner: '>=2.1.2 <3.0.0'
  build_test:
